apiVersion: v1
kind: Service
metadata:
  name: argo-web-service
  namespace: argo-web
spec:
  type: NodePort
  selector:
    app: argo-web
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
      nodePort: 30080
