apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web
  namespace: k8s-web
spec:
  selector:
    matchLabels:
      app: k8s-web
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-web
    spec:
      containers:
        - name: k8s-web
          image: k8sweb:v1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
