apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-web
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RobDaPraia/hello-world-argo
    targetRevision: main
    path: argo-templates/argo-web
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-web
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
